# Site settings
title: Wedding!
email: lizzieandhamish@gmail.com
url: https://lizzieandhamish.co.uk
description: "Lizzie Coyle and Hamish Henderson are getting Married!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#F9EACC'
  # primary-dark: '#F4E2BE'
  links: '#62892A'

# Footer settings
footer: Lizzie & Hamish


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: facebook
#     url: https://facebook.com

site-map:
    home:
        title: home
        sections:
            - about
            - how_long
            - contact
            - map
        menu:
            - the-day
            - accommodation
            - rsvp
            - giftlist
    about:
        title: Welcome!
    how_long:
        title: How Long?
    contact:
        title: Contact Us
    map:
        title: Where?
    ceremony:
        title: Ceremony
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
    reception:
        title: Evening
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
    the-day:
        title: The Big Day
        submenu:
            - ceremony
            - reception
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
    accommodation:
        title: Accommodation
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
    rsvp:
        title: RSVP
        path: rsvp
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
    giftlist:
        title: Gift List
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist



# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-babel

# babel_js_extensions: 'es6, babel, jsx'
